ogr-decode --all-threads --max-segment 500 --area-type Urban work/Urban data/shapefiles/haw_urban                                                                                                                                                          
ogr-decode --all-threads --max-segment 500 --area-type Town work/Town data/shapefiles/haw_town                                                                                                                                                           
ogr-decode --all-threads --max-segment 500 --area-type Industrial work/Industrial data/shapefiles/haw_industrial                                                                                                                                                     
ogr-decode --all-threads --max-segment 500 --area-type Transport work/Transport data/shapefiles/haw_transport                                                                                                                                                      
ogr-decode --all-threads --max-segment 500 --area-type Port work/Port data/shapefiles/haw_port                                                                                                                                                           
ogr-decode --all-threads --max-segment 500 --area-type Airport work/Airport data/shapefiles/haw_airports                                                                                                                                                       
ogr-decode --all-threads --max-segment 500 --area-type OpenMining work/OpenMining data/shapefiles/haw_openmining                                                                                                                                                     
ogr-decode --all-threads --max-segment 500 --area-type Dump work/Dump data/shapefiles/haw_dump                                                                                                                                                           
ogr-decode --all-threads --max-segment 500 --area-type Construction work/Construction data/shapefiles/haw_construction                                                                                                                                                   
ogr-decode --all-threads --max-segment 500 --area-type Greenspace work/Greenspace data/shapefiles/haw_greenspace
ogr-decode --all-threads --max-segment 500 --area-type GolfCourse work/GolfCourse data/shapefiles/haw_leisure
ogr-decode --all-threads --max-segment 500 --area-type DryCrop work/DryCrop data/shapefiles/haw_drycrop
ogr-decode --all-threads --max-segment 500 --area-type IrrCrop work/IrrCrop data/shapefiles/haw_irrcrop
ogr-decode --all-threads --max-segment 500 --area-type Rice work/Rice data/shapefiles/haw_rice
ogr-decode --all-threads --max-segment 500 --area-type Vineyard work/Vineyard data/shapefiles/haw_vineyard
ogr-decode --all-threads --max-segment 500 --area-type Orchard work/Orchard data/shapefiles/haw_orchard
ogr-decode --all-threads --max-segment 500 --area-type Olives work/Olives data/shapefiles/haw_olives
ogr-decode --all-threads --max-segment 500 --area-type MixedCrop work/MixedCrop data/shapefiles/haw_pasture
ogr-decode --all-threads --max-segment 500 --area-type MixedCrop work/MixedCrop data/shapefiles/haw_mixedcrop
ogr-decode --all-threads --max-segment 500 --area-type ComplexCrop work/ComplexCrop data/shapefiles/haw_complexcrop
ogr-decode --all-threads --max-segment 500 --area-type NaturalCrop work/NaturalCrop data/shapefiles/haw_naturalcrop
ogr-decode --all-threads --max-segment 500 --area-type AgroForest work/AgroForest data/shapefiles/haw_agroforest
ogr-decode --all-threads --max-segment 500 --area-type DeciduousForest work/DeciduousForest data/shapefiles/haw_deciduousforest
ogr-decode --all-threads --max-segment 500 --area-type EvergreenForest work/EvergreenForest data/shapefiles/haw_evergreenforest
ogr-decode --all-threads --max-segment 500 --area-type MixedForest work/MixedForest data/shapefiles/haw_mixedforest
ogr-decode --all-threads --max-segment 500 --area-type Grassland work/Grassland data/shapefiles/haw_grassland
ogr-decode --all-threads --max-segment 500 --area-type Heath work/Heath data/shapefiles/haw_heath
ogr-decode --all-threads --max-segment 500 --area-type Sclerophyllous work/Sclerophyllous data/shapefiles/haw_sclerophyllous
ogr-decode --all-threads --max-segment 500 --area-type Scrub work/Scrub data/shapefiles/haw_scrub
ogr-decode --all-threads --max-segment 500 --area-type Sand work/Sand data/shapefiles/haw_sand
ogr-decode --all-threads --max-segment 500 --area-type Rock work/Rock data/shapefiles/haw_rock
ogr-decode --all-threads --max-segment 500 --area-type BarrenCover work/BarrenCover data/shapefiles/haw_barrencover
ogr-decode --all-threads --max-segment 500 --area-type Burnt work/Burnt data/shapefiles/haw_burnt
ogr-decode --all-threads --max-segment 500 --area-type Glacier work/Glacier data/shapefiles/haw_glacier
ogr-decode --all-threads --max-segment 500 --area-type Marsh work/Marsh data/shapefiles/haw_marsh
ogr-decode --all-threads --max-segment 500 --area-type Bog work/Bog data/shapefiles/haw_bog
ogr-decode --all-threads --max-segment 500 --area-type SaltMarsh work/SaltMarsh data/shapefiles/haw_saltmarsh
ogr-decode --all-threads --max-segment 500 --area-type Saline work/Saline data/shapefiles/haw_saline
ogr-decode --all-threads --max-segment 500 --area-type Intertidal work/Intertidal data/shapefiles/haw_intertidal
ogr-decode --all-threads --max-segment 500 --area-type Watercourse work/Watercourse data/shapefiles/haw_river
ogr-decode --all-threads --max-segment 500 --area-type Lake work/Lake data/shapefiles/haw_lake
ogr-decode --all-threads --max-segment 500 --area-type Lagoon work/Lagoon data/shapefiles/haw_lagoon
ogr-decode --all-threads --max-segment 500 --area-type Estuary work/Estuary data/shapefiles/haw_estuary
ogr-decode --all-threads --max-segment 500 --area-type HerbTundra work/HerbTundra data/shapefiles/haw_herb

 
